apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-application
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-application
    spec:
      containers:
      - name: flask
        image: ./flask
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      - name: nginx
        image: soumyasen/docker_build_repo:01
        imagePullPolicy: Always
        ports:
          - containerPort: 80
