apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: soumyasen/docker_build_repo:01
        imagePullPolicy: Always
        ports:
        - containerPort: 80
